In [1]:
print("hello")

hello


In [2]:
a=10
b=20
var1=input("enter a number:")
var2=input("enter another number:")
print(var1+var2)

2316


In [4]:
import numpy as np
arr1=np.array([2,4,6,8,10])
print(arr1)
arr1.ndim



[ 2  4  6  8 10]


1

In [5]:
arr1+1

array([ 3,  5,  7,  9, 11])

In [6]:
arr1[:]

array([ 2,  4,  6,  8, 10])

In [7]:
arr1[:]=10

In [9]:
arr1[1]=20
arr1

array([10, 20, 10, 10, 10])

In [5]:
arr2=np.array([1,2,3,4,5,6])
arr2.shape

(6,)

2D arrays

In [12]:
arr3=np.array([[1,2,3,4],[1,2,3,4]])
arr3
arr3.shape
arr3.ndim
arr3.size
arr3.dtype


8

In [32]:
arr3[1,3]
arr3[0,2]=5
arr3
arr3[-1,-1]
arr3[:,2]
arr3[:,2]=[6,6]
arr3[0:2,1:3]=0
arr3

array([[1, 0, 0, 4],
       [1, 0, 0, 4]])

In [31]:
arr4=np.array([[1,2,3],[2,4,6],[3,6,9],[4,8,12],[5,10,15],[6,12,18],[7,14,21]])
arr4
arr4.shape
arr4[:,::2]
arr4[::6,::2]=0
arr4

array([[ 0,  2,  0],
       [ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18],
       [ 0, 14,  0]])

Advanced indexing

In [39]:
arr4[[0,2,4,6],[0,2,0,2]]
arr4[[0,2,4,6],[0,2,0,2]]=100
arr4
arr4[[0,1,4]]=255
arr4

array([[255, 255, 255],
       [255, 255, 255],
       [  3,   6, 100],
       [  4,   8,  12],
       [255, 255, 255],
       [  6,  12,  18],
       [  0,  14, 100]])

In [43]:
arr4>100
arr4[arr4>100]=0
arr4
arr4[arr4%2==0]

array([  0,   0,   0,   0,   0,   0,   6, 100,   4,   8,  12,   0,   0,
         0,   6,  12,  18,   0,  14, 100])

In [46]:
arr5=np.random.randint(1,100,(7,3))
arr5
arr5[arr5%2==0]

array([30, 78, 24, 24, 74, 42, 62, 34, 80, 10], dtype=int32)

Homework

In [7]:
#boolean indexing on 1D array
import numpy as np
arr=np.array([12,45,7,19,34,28,90,55,63])
#1 all elements greater than 30
arr[arr>30]
#2 extract all odd numbers
arr[arr%2!=0]
#3 replace all numbers that are multiples of 5 with -1
arr[arr%5==0]=-1
arr
#4 count how mamy numbers are less than 50
arr=np.array([12,45,7,19,34,28,90,55,63])
arr[arr<50].size

6

In [8]:
#boolean indexing on a 2D array
arr=np.array([[10,25,40],[55,18,72],[91,30,64]])
#1 extract all numbers greater than 50
arr[arr>50]
#2 replace all even numbers with 0
arr[arr%2==0]=0
arr
#3 find the sum of all numbers that are divisible by 5
arr=np.array([[10,25,40],[55,18,72],[91,30,64]])
sum(arr[arr%5==0])
#4 count how many numbers are greater than 20 but less than 70
arr=np.array([[10,25,40],[55,18,72],[91,30,64]])
arr[(arr>20)&(arr<70)].size

5

In [5]:
#fancy indexing
arr=np.array([[12,34,56],[78,90,23],[45,67,89]])
arr
#1 extract elements from first and third row
arr[::2,::]
#2 extract second coloumn from the array
arr[::,1]
#3 extract specific elements 12,90,67 using advanced indexing
arr[[0,1,2],[0,1,1]]
#4 swap the first and last row of the array
arr=np.array([[12,34,56],[78,90,23],[45,67,89]])
arr[[0,2]]=arr[[2,0]]
arr


array([[45, 67, 89],
       [78, 90, 23],
       [12, 34, 56]])

In [9]:
#mixing boolean and fancy indexing
import numpy as np
arr=np.array([[5,15,25],[35,45,55],[65,75,85]])
arr
#1 extract all numbers that are multiples of 5 and greater than 30
arr[(arr%5==0)&(arr>30)]
#2 replace all numbers less than 50 with -1
arr[arr<50]=-1
arr
#3 extract the last column and replace all vsalues with 100
arr=np.array([[5,15,25],[35,45,55],[65,75,85]])
arr[::,-1]=100
arr
#4 create a new array where all values geater than 60 are doubled
arr=np.array([[5,15,25],[35,45,55],[65,75,85]])
arr[arr>60]=arr[arr>60]*2
arr

array([35, 45, 55, 65, 75, 85])

In [22]:
#sum
arr=np.array([[5,15,25],[35,45,55],[65,75,85]])
np.sum(arr)
np.sum(arr,axis=1)
np.sum(arr,axis=0)
#min
np.min(arr)
np.min(arr,axis=1)
np.min(arr,axis=0)
#max
np.max(arr)
np.max(arr,axis=1)
np.max(arr,axis=0)
#mean
#median
#std
#var
#argmax
np.argmax(arr)
np.argmax(arr,axis=1)
np.argmax(arr,axis=0)
#argmin

array([2, 2, 2])

In [35]:

#zeros
arr=np.zeros((10,5))
#ones
np.ones((4,4))
#full
np.full((5,7),8)
#full_like
np.full_like(arr,9)
#arange
np.arange(1,11,2)
b=np.arange(100,0,-1)
#reshape
b.reshape((10,10))
np.reshape(arr,(1,50))


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]])